variables:
  IMAGE_NAME_DEVELOPMENT: $CI_REGISTRY/ketty/editoria/editoria-dev
  WORKDIR: /home/node/app

stages:
  - build development
  - lint
  - build preproduction
  - publish
  - deploy

build:
  image: docker:26
  stage: build development
  services:
    - docker:26-dind
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
  script:
    - docker build --tag $IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_SHA -f Dockerfile-development .
    - docker push $IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_SHA

lint:
  stage: lint
  image: $IMAGE_NAME_DEVELOPMENT:$CI_COMMIT_SHA
  script:
    - cd $WORKDIR
    - yarn coko-lint run
