FROM node:16.19.0-bullseye

RUN apt-get update && \
    apt-get install -y ranger vim python

WORKDIR /home/node/app

COPY package.json .
COPY ./public ./public

COPY yarn.lock .
RUN yarn install --frozen-lockfile

USER node
COPY --chown=node:node . .
